"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-itvrl_2!%fe$a!iwate&g^m$omyf%f^6$5u0wdod%$do0kn%yo'

DEBUG = True

ALLOWED_HOSTS = []


# ============ APP LAR ============
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bizning app'lar
    'pages',
    'products',
]


# ============ MIDDLEWARE ============
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'


# ============ SHABLONLAR (TEMPLATES) ============
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # asosiy templates papka
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# ============ DATABASE ============
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============ PAROL SIYOSATI ============
AUTH_PASSWORD_VALIDATORS = []


# ============ TIL VA VAQT SOZLAMALARI ============
LANGUAGE_CODE = 'uz'
TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_TZ = True


# ============ STATIK FAYLLAR ============
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# ============ MEDIA FAYLLAR ============
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============ BAZA ID TURLARI ============
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
